### ISSUE TITLE
Don't overwrite reducers when starting to sync

### ISSUE THREAD

**Issue by SBoudrias** [redbooth/backbone-redux#10]
If you have a store with reducers already defined, `syncCollection` will overwrite them.

It'd be nice if backbone-redux was a bit more friendly to the Redux API.

I guess the main problem is that backbone-redux need to have an handle on the dispatch method. So maybe backbone-redux could be a middleware:

`compose(syncCollections({...conf}))(createStore)`

**Comment by somebody32** [comment]
@SBoudrias This is needed because `syncCollection` is adding newly generated reducers to the store.
But you can pass the third param to `syncCollections` — [`extraReducers`](https://github.com/redbooth/backbone-redux#synccollectionscollectionmap-store-extrareducers-), that will bundle these reducers together with generated ones. Will that work for you?

**Comment by SBoudrias** [comment]
Hey, that's what I did and it's working indeed. My issue is that it's not very Redux like - so I was trying to suggest ways we could make the API friendly to the Redux ecosystem.

**Comment by somebody32** [comment]
@SBoudrias I will be glad to do that, but I'm not seeing any other option: we need to create new reducers and add them somehow to the store. Having middleware is great, but it can operate only at the moment of dispatching. Or maybe I misread your idea?

**Comment by somebody32** [comment]
I will close this for now as soon as I can't see any actionable item out of it. But really feel free to comment or re-open it if you have any ideas how to make the API better and more redux-friendly
